package vista;

import Modelo.ClasePostales;
import Modelo.DoublyLinkedList;
import Modelo.PostalesDAO;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class TodosLosPersonajes extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    
    public TodosLosPersonajes() {
        initComponents();
        lblIdPerfil.setText(Album.lblIdUsuario.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lblPersonaje = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        head = new javax.swing.JPanel();
        btnSalir = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblMiId = new javax.swing.JLabel();
        lblIdPerfil = new javax.swing.JLabel();
        lblPath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPersonaje.setBackground(new java.awt.Color(0, 0, 0));
        lblPersonaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPersonaje.setForeground(new java.awt.Color(255, 255, 0));
        lblPersonaje.setText("                         PERSONAJE");
        lblPersonaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        bg.add(lblPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 290, 395));

        btnSiguiente.setBackground(new java.awt.Color(0, 0, 0));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 0));
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.setBorder(null);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        bg.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 120, 40));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 0));
        btnVolver.setText("VOLVER");
        btnVolver.setBorder(null);
        bg.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 130, 40));

        head.setBackground(new java.awt.Color(0, 0, 0));
        head.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headMouseDragged(evt);
            }
        });
        head.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headLayout = new javax.swing.GroupLayout(head);
        head.setLayout(headLayout);
        headLayout.setHorizontalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        headLayout.setVerticalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 30));

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 0, 0));
        btnSalir.setText("   X");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        bg.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 30));

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 0));
        lblTitulo.setText("TODOS LOS PERSONAJES");
        bg.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        lblMiId.setBackground(new java.awt.Color(0, 0, 0));
        lblMiId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMiId.setForeground(new java.awt.Color(255, 255, 0));
        lblMiId.setText("Mi id:");
        bg.add(lblMiId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lblIdPerfil.setBackground(new java.awt.Color(0, 0, 0));
        lblIdPerfil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdPerfil.setForeground(new java.awt.Color(255, 255, 0));
        lblIdPerfil.setText(".");
        bg.add(lblIdPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 30, -1));

        lblPath.setBackground(new java.awt.Color(0, 0, 0));
        lblPath.setForeground(new java.awt.Color(51, 51, 51));
        lblPath.setText(".");
        bg.add(lblPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setForeground(Color.yellow);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setForeground(Color.red);
    }//GEN-LAST:event_btnSalirMouseExited

    private void headMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headMousePressed

    private void headMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headMouseDragged

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        PostalesDAO dao = new PostalesDAO();
        ClasePostales postales = new ClasePostales();
        DoublyLinkedList lista = new DoublyLinkedList();
        
        postales.setIdPerfil(Integer.parseInt(lblIdPerfil.getText()));
        dao.ListaTodos(postales);

//        ClasePostales postales = new ClasePostales();
//        DoublyLinkedList lista = new DoublyLinkedList();
//        
//        postales.setIdPerfil(Integer.parseInt(lblIdPerfil.getText()));
//        lista.insert(postales);
//        lista.print();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TodosLosPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TodosLosPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TodosLosPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TodosLosPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TodosLosPersonajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    public javax.swing.JLabel btnSalir;
    public javax.swing.JButton btnSiguiente;
    public javax.swing.JButton btnVolver;
    public javax.swing.JPanel head;
    public javax.swing.JLabel lblIdPerfil;
    public javax.swing.JLabel lblMiId;
    public javax.swing.JLabel lblPath;
    public javax.swing.JLabel lblPersonaje;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
